version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /src/web
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/api
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /src/api.tests
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
